# Generated by Django 3.1.6 on 2021-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uks_app', '0003_auto_20210220_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
